os: Visual Studio 2015

environment:
  matrix:
    - BUILD_PROFILE: ci_part1
    - BUILD_PROFILE: ci_part2

init: 
build_script: 
  - cmd: build.cmd %BUILD_PROFILE%

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch

test: off 
version: 0.0.1.{build} 
artifacts: 
  - path: Release
    name: Release