os: Visual Studio 2015

init: 
build_script: 
  - cmd: appveyor-build.cmd

# scripts that run after cloning repository
install:
  # by default, all script lines are interpreted as batch

test: off 
version: 0.0.1.{build} 
artifacts: 
  - path: Release
    name: Release
